repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types:
          - python3
          - python


      - id: isort (python)
        name: isort
        entry: isort
        require_serial: true
        language: python
        types_or:
          - python
          - python3
          - cython
          - pyi
        args:
          - --filter-files
        minimum_pre_commit_version: '2.9.2'


      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types_or:
          - python
          - python3
          - pyi
          - cython
